package com.fiedormichal.postrestapi.apierror;

public enum ApiErrorMsg {
    MISMATCH_TYPE,
    VALIDATION_ERRORS,
    MALFORMED_JSON_REQUEST,
    UNSUPPORTED_MEDIA_TYPE,
    METHOD_NOT_FOUND,
    POST_NOT_FOUND,
    API_CONNECTION_FAILURE,
    USER_NOT_FOUND,
    POSTS_NOT_FOUND,
    CONSTRAINT_VIOLATIONS,
    ERROR_OCCURRED;
}
